### ISSUE TITLE
Proposal: Adding 'since' attribute to rules documenation

### ISSUE THREAD

**Issue by ajmas** [vuejs/eslint-plugin-vue#1379]
Proposing the addition of a 'since' attribute to be added to the front-matter of the rules documentation. This would be used to indicate since what version of eslint-plugin-vue a given rule exists. 

This proposal is in the context that not everyone has the latest version of eslint-plugin-vue (such as in a corporate environment), but may be looking at the documentation. It would give them a hint whether the rule was addd prior or after the version of eslint-plugin-vue being used in the project.

Example

```md
---
pageClass: rule-details
sidebarDepth: 0
title: vue/no-unused-properties
description: disallow unused properties
since: v7.1.0
---
...
```

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

You can refer to the release notes to find out when the rule was added.
https://github.com/vuejs/eslint-plugin-vue/releases

You can also refer to the tag to check for old documents.
https://github.com/vuejs/eslint-plugin-vue/blob/v6.2.2/docs/rules/README.md

If you still need `since`, could you open a PR?

**Comment by ajmas** [comment]
I’ll do the work and make a PR.

**Comment by ajmas** [comment]
The current PR adds the since tag, but not familiar enough with VuePress to have it reflected on the rendered page.

**Comment by ota-meshi** [comment]
Thank you for your contribution.
I also changed it to add a version at the bottom of the documentation for each rule.

![image](https://user-images.githubusercontent.com/16508807/103055928-e3b0c080-45de-11eb-95fc-646470dd24f1.png)
