### ISSUE TITLE
Summary of eslint-plugin-vue v9

### ISSUE THREAD

**Issue by ota-meshi** [vuejs/eslint-plugin-vue#1850]
I am planning a major version upgrade of eslint-plugin-vue.
Mainly due to the breaking changes caused by the parser upgrade, a major version upgrade is required.

I started some necessary work with the following PR.

- #1846
- #1847
- #1848
- #1849
- #1881
- #1883
- #1851
- #1892

Please leave a comment on this issue if you think we have other work to do.

@FloEdelmann

**Comment by ota-meshi** [comment]
It will be released after May as it must be after Node.js v12 is no longer supported.
However, we may release an alpha version before that.

**Comment by FloEdelmann** [comment]
This issue should also be fixed in the next major release (since the bug fix could also be considered a breaking change):

* #1879

**Comment by FloEdelmann** [comment]
Let me try to draft the release notes here (feel free to edit this comment @ota-meshi!):

---

# v9.0.0

## 💥 Breaking Changes

* [#1847](https://github.com/vuejs/eslint-plugin-vue/pull/1847) Drop support for Node.js v12.
* [#1846](https://github.com/vuejs/eslint-plugin-vue/pull/1846) Change default casing of [`vue/custom-event-name-casing`](https://eslint.vuejs.org/rules/custom-event-name-casing.html) rule to `camelCase`.
* [#1883](https://github.com/vuejs/eslint-plugin-vue/pull/1883) Potentially breaking bug fix: Enable [`vue/html-closing-bracket-spacing`](https://eslint.vuejs.org/rules/html-closing-bracket-spacing.html) and [`vue/html-closing-bracket-newline`](https://eslint.vuejs.org/rules/html-closing-bracket-newline.html) rules for top-level tags.
* [#1848](https://github.com/vuejs/eslint-plugin-vue/pull/1848) Change presets configs and remove unused internal methods. *(see below)*
* [#1849](https://github.com/vuejs/eslint-plugin-vue/pull/1849) Upgrade [vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser) to v9. *(see below)*
* [#1881](https://github.com/vuejs/eslint-plugin-vue/pull/1881) Remove deprecated rules. *(see below)*

### Change Vue 3 presets configs

* Change `plugin:vue/vue3-essential` config:
  - Add [`vue/no-child-content`](https://eslint.vuejs.org/rules/no-child-content.html) rule
  - Add [`vue/no-expose-after-await`](https://eslint.vuejs.org/rules/no-expose-after-await.html) rule
  - Add [`vue/no-reserved-component-names`](https://eslint.vuejs.org/rules/no-reserved-component-names.html) rule
  - Add [`vue/no-use-computed-property-like-method`](https://eslint.vuejs.org/rules/no-use-computed-property-like-method.html) rule
  - Add [`vue/no-v-text-v-html-on-component`](https://eslint.vuejs.org/rules/no-v-text-v-html-on-component.html) rule
  - Add [`vue/prefer-import-from-vue`](https://eslint.vuejs.org/rules/prefer-import-from-vue.html) rule
* Change `plugin:vue/vue3-strongly-recommended` config:
  - Same changes as above
* Change `plugin:vue/vue3-recommended` config:
  - Same changes as above

### Change Vue 2 preset configs

* Change `plugin:vue/essential` config:
  - Add [`vue/no-child-content`](https://eslint.vuejs.org/rules/no-child-content.html) rule
  - Add [`vue/no-reserved-component-names`](https://eslint.vuejs.org/rules/no-reserved-component-names.html) rule
  - Add [`vue/no-use-computed-property-like-method`](https://eslint.vuejs.org/rules/no-use-computed-property-like-method.html) rule
  - Add [`vue/no-v-text-v-html-on-component`](https://eslint.vuejs.org/rules/no-v-text-v-html-on-component.html) rule
  - Add [`vue/valid-model-definition`](https://eslint.vuejs.org/rules/valid-model-definition.html) rule
  - Add [`vue/no-export-in-script-setup`](https://eslint.vuejs.org/rules/no-export-in-script-setup.html) rule \*
  - Add [`vue/no-ref-as-operand`](https://eslint.vuejs.org/rules/no-ref-as-operand.html) rule \*
  - Add [`vue/no-setup-props-destructure`](https://eslint.vuejs.org/rules/no-setup-props-destructure.html) rule \*
  - Add [`vue/return-in-emits-validator`](https://eslint.vuejs.org/rules/return-in-emits-validator.html) rule \*
  - Add [`vue/valid-define-emits`](https://eslint.vuejs.org/rules/valid-define-emits.html) rule \*
  - Add [`vue/valid-define-props`](https://eslint.vuejs.org/rules/valid-define-props.html) rule \*
* Change `plugin:vue/strongly-recommended` config:
  - Same changes as above
* Change `plugin:vue/recommended` config:
  - Same changes as above

*Note:* The rules marked with \* are now included in the `plugin:vue/essential` config because [`@vue/composition-api`](https://github.com/vuejs/composition-api) and [`unplugin-vue2-script-setup`](https://github.com/antfu/unplugin-vue2-script-setup/) add (limited) support for these features in Vue 2. If you don't use those libraries, enabling these rules shouldn't affect you.

### Deprecated features

* `vue/no-invalid-model-keys` rule is now deprecated, as it's renamed to [`vue/valid-model-definition`](https://eslint.vuejs.org/rules/valid-model-definition.html)
* `vue/script-setup-uses-vars` rule is now deprecated, as it's no longer needed with the upgrade to [vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser) to v9
* `vue/setup-compiler-macros` environment is now deprecated, as it's no longer needed with the upgrade to [vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser) to v9

### Remove features

Previously deprecated rules are removed completely:

* `vue/experimental-script-setup-vars` rule (deprecated in v7.13.0): not needed anymore
* `vue/name-property-casing` rule (deprecated in v7.0.0): use [`vue/component-definition-name-casing`](https://eslint.vuejs.org/rules/component-definition-name-casing.html) instead
* `vue/no-confusing-v-for-v-if` rule (deprecated in v5.0.0): use [`vue/no-use-v-if-with-v-for`](https://eslint.vuejs.org/rules/no-use-v-if-with-v-for.html) instead
* `vue/no-unregistered-components` rule (deprecated in v8.4.0): use [`vue/no-undef-components`](https://eslint.vuejs.org/rules/no-undef-components.html) instead

Previously deprecated internal util methods are removed completely:

* `getComponentProps`: use `getComponentPropsFromOptions` instead
* `getComponentEmits`: use `getComponentEmitsFromOptions` instead

## ✨ Enhancements

* [#1874](https://github.com/vuejs/eslint-plugin-vue/pull/1874) Make [`vue/match-component-file-name`](https://eslint.vuejs.org/rules/match-component-file-name.html) rule fixable via editor suggestions.

## 🐛 Bug Fixes

* [#1861](https://github.com/vuejs/eslint-plugin-vue/pull/1861) Fix wrong behavior of [`vue/define-macros-order`](https://eslint.vuejs.org/rules/define-macros-order.html) rule when there are multiple `<script>` tags.
* [#1883](https://github.com/vuejs/eslint-plugin-vue/pull/1883) Potentially breaking bug fix: Enable [`vue/html-closing-bracket-spacing`](https://eslint.vuejs.org/rules/html-closing-bracket-spacing.html) and [`vue/html-closing-bracket-newline`](https://eslint.vuejs.org/rules/html-closing-bracket-newline.html) rules for top-level tags.

**Comment by FloEdelmann** [comment]
So now all PRs mentioned in this issue are merged. Is there anything missing for the release?

**Comment by ota-meshi** [comment]
If possible, I would like to merge the rule implemented in #1851 and include this rule in `essential`. However, it is not required. I want to wait until next week to see if there is any progress.

**Comment by ota-meshi** [comment]
I have released v9 🎉
So I close this issue.
