### ISSUE TITLE
FYI: typescript-eslint@v6 will remove parserServices.hasFullTypeInformation

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vuejs/eslint-plugin-vue#2227]
👋 Hi! I'm one of the maintainers of [typescript-eslint](https://typescript-eslint.io). We're getting ready to release a new v6 major version of the tooling, which includes some small breaking changes.

Coming over from https://github.com/typescript-eslint/typescript-eslint/issues/7124: I see this repo contains references to `hasFullTypeInformation`. That property is something we've never recommended using (see that issue & https://github.com/typescript-eslint/typescript-eslint/issues/7158). We recommend instead using `ESLintUtils.getParserServices` per https://typescript-eslint.io/developers/custom-rules#typed-rules.

If you _really_ want to "progressively enhance" lint rules, `parserServices.program` will be `null` if type information isn't available. But we definitely recommend against that kind of rule behavior changing.

Overall, I'd suggest trying out typescript-eslint@v6 and making sure internal builds & downstream repos still compile & lint nicely with all the changes. Let me know if there's anything we can do to help with the v6 upgrade! 💖

**Comment by ota-meshi** [comment]
Thank you for letting me know.
I would avoid using `ESLintUtils.getParserServices` because `@typescript-eslint/utils` is too many dependencies for us. I especially don't want TypeScript to be installed in the environment of users who don't use TypeScript. So I think maybe we implement our own function.

> we've never recommended

I didn't know it was never recommended 😅. I was referring to the source code of someone who used to belong to your team.
https://github.com/mysticatea/eslint-plugin-es/blob/00d73851793541dc7b0d07292deb0ca2bc8a25e1/lib/util/define-prototype-method-handler.js#L27
I need to modify the source code that I created with reference to it.
