### ISSUE TITLE
pug templates not getting lint

### ISSUE THREAD

**Issue by metaory** [vuejs/eslint-plugin-vue#310]
* **ESLint Version: 4.14.0**
* **eslint-plugin-vue Version: 4.0.0-beta.4**
* **Node Version: 9.2.0**

```
module.exports = {
  root: true,
  parserOptions: {
    'parser': 'babel-eslint',
    'ecmaVersion': 2017,
    'ecmaFeatures': {
      'experimentalObjectRestSpread': true
    },
    'sourceType': 'module'
  },
  env: {
    browser: true,
    es6: true
  },
  'extends': [
    'google',
    'plugin:vue/recommended'
  ],
  plugins: [ ],
  settings: {
    'import/resolver': {
      webpack: {
        config: 'build/webpack.base.conf.js'
      }
    }
  },
  globals: {    'Vue': true  },
  rules: {  }
}
```

none of rules getting checked on pug templates
```
<template lang="pug">
  div
    ol(v-for="i in 5")
      li foobar
</template>
```

it works fine on html templates
```
<template>
  <div>
    <ol v-for="i in 5">
      <li>item</li>
    </ol>
  </div>
</template>
```

**pug templates not getting lint**

**Comment by mysticatea** [comment]
Thank you for the report.

Unfortunately, this plugin has not supported pug yet.
I have a plan to lint pug in future, but it's not soon.

**Comment by Alendorff** [comment]
Hello, just wondering if there are any plans for pug support?

**Comment by rossity** [comment]
@mysticatea @michalsnik can we get an update on your plans for pug support? it's a sorely needed feature!

**Comment by LeCoupa** [comment]
Any plans for pug support?

**Comment by michalsnik** [comment]
No plans so far here. Please fire an issue in `vue-eslint-parser` - once it supports PUG we'll be able to support it too.

**Comment by Shinigami92** [comment]
Author of https://github.com/prettier/plugin-pug here.

Please `watch/star` https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc
I will try to tackle eslint vue pug support in next time

**Comment by Shinigami92** [comment]
https://www.npmjs.com/package/eslint-plugin-vue-pug-sfc/v/1.0.0-alpha.2 :eyes: 

This is a first alpha and "supports" `vue-pug-sfc/this-in-template` for the `never` option. `always` is currently **NOT** supported due to it is much harder to implement.

Please give it a try and please also start to create issues in the [repo](https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc) for every rule you want to get support for!
Please do **NOT** use the `--fix` option right know (or at least with a backup), cause it can damage your code!
The `ranges` are not accurate yet so the `~~~~` lines are positioned to broad right now.

Please also feel free to jump into the code and help me :smiley:
If you use VSCode jump into the Debug Launcher and run the tests with debug-breakpoints.

---

I will not _spam_ here anymore, so please lets move all discussions to the project's [repo](https://github.com/Shinigami92/eslint-plugin-vue-pug-sfc).

**Comment by rashfael** [comment]
Pug support has been added via [eslint-plugin-vue-pug](https://github.com/rashfael/eslint-plugin-vue-pug), which adds a template tokenizer to vue-eslint-parser, making a lot of rules of [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) just work.
For full rule compat see [this table](https://github.com/rashfael/eslint-plugin-vue-pug/tree/main/docs/rules).
Please try it out on your real world projects and see if you can find some bugs!
