### ISSUE TITLE
directive-comment cannot disable max-lines rule

### ISSUE THREAD

**Issue by bozzaj** [vuejs/eslint-plugin-vue#335]
eslint-plugin-vue Version: 4.1.0
eslint Version: 4.14.0

Attempting to use the rule:
`<!-- eslint-disable max-lines -->`

at the beginning of a large file that starts with HTML (such as a single file component) won't actually disable the rule. It'll just move the error to the comment line. It seems to be the use of `comment.loc.start` within processBlock() which doesn't actually start at the beginning of the line. A possible fix would be to replace this with:
`{ line: comment.loc.start.line, column: -1 }`

which seems to work fine.

**Comment by mysticatea** [comment]
Thank you for the report.

This is intentional behavior. `eslint-disable` comment does not disable errors before the comment. This is the same behavior as the core `eslint-disable`. See [online demo](https://eslint.org/demo/#eyJ0ZXh0IjoiYSAvKiBlc2xpbnQtZGlzYWJsZSBtYXgtbGluZXMgKi9cclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuYVxyXG5hXHJcbmFcclxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im1heC1saW5lcyI6Mn0sImVudiI6e319fQ==)

**Comment by bozzaj** [comment]
I see (and understand) what you mean with the online demo. However, this is not the same behavior as core eslint-disable, at least not for max-lines. To properly disable the max-lines rule, you need to have the disable at the very beginning of the file. 

For a .js file, you place at the beginning of the file:
`/* eslint-disable max-lines */`

and then the rule is disabled for that file. However, if I do the same thing in a .vue file using this plugin, the max-lines rule is not disabled. I get an error at the comment still saying that the file fails the max-lines. 

See [Vue eslint demo](https://mysticatea.github.io/vue-eslint-demo/#eJztWc1unDAQfhXEpW207ko9rlaVqkp9gfaYi4EB3Bibju3Nkijv3rEBYyCV+gAcsmG+sT1/34z35zUvdQX5JT8/ZGCkUJZVwvBCQtbxOyMATPZwflRXC10vuYWvjyrLrpW4hYfxMTsfwiEcwiEcwiEcwiEcwiEcwiEcwiEcQhSu5yp8cL6ek4/TV1Oi6C09wb3XaLMKau6kzV79FsU7uGQfvvX9h9Oj8kgHttWVuYz6LNPquxTl08dPM5Bl53NW6cxov1So5vOIv/l/9PLmHZiM5qccnQSTX17zUitj0ZVWIzOuB8wvX065UBUoGx7jVwJBUpqV3ACroJQcuRW0PSokN4bRn2hUxHTXcwSmoGEvgHrBVbVbqoyWkIr2nSWWKxu2C2880VjUkiE0cJ/BCgrXNFNIQZZggd34glDEjGNjVsAYSAddAbjWPMGQAlQCKmfIyIxSie3AypaSU1rA8ay1sueWNGoFRuG+CRnuFjkrNGWGK2/JrjUGOjEjNZfStqhd00bIqXJzYiN1weUGFEqRs+9VVagbl6IaM9tHFEl2tJg9t8KC6XkZU9CJO1QsQEQHqrPlRTxOwTMzQ1doOSO6+E1xSRmX6NLyqEUYnYIFID+m02fMgKw3AdECNL62yJeSUWMYVkCtiZEL2UnhiO/1IlCgQNWrWEctKTz7Fx0Cp+oWMoEMr4HVQlEQwwYl3vOUp045Q+dKXsAS8AQSLxeIQgIiIZiS96MpyhM5xUxL46KltAYQ4Y8TFM0gQI4I7WTCKD6aHGtnhx70GN/NwZn4h6JwxNx26FtQi4de29pOMghlm/oioslYiNgfpy1s1oV6lFIbmkNR89vcfVhmidOjfrxEfwyjmrCY76B31PFlSzEpappey+BsqH96uJ+YrEdN+3378ZVlyic3AzWCUGEgOV/aabFIfB/nSO38ZnZjRBN6FXWqX0+BBZwmwRJJqg8sSik74Z6i3hQgakwVCAbwRk5uLRmaKwT7ILQC/8Utt3y1QFTAoK6JKeY/wp1vJG9ojd8tWeJsTn+q3NLVwxorqtxkMLi26GaOLl6LvXK6/4KfO6UHA4n3+5CYSpYRrEO1045FTIOLmtAY/7Dqz3ove8sxYZLQijmBUXFjBXUJM3aQKegpu4bGxpzzj1rbjW48aQdSW/GnHUrTBFKqpvgOrBO2zZjv2x34zoGdplt0hybjY4HKveUe9xgNtOcd6AlI4Nv8VuSneIHkncmvwQ/FfLx2TjnQmwGNE+h/3Pimqh/+Fvruf+g45eEuoJhzuqgQIH/7C5XiQT0=)

Perhaps my bug notification referenced the new directive-comment, but I see now that's it's a general issue with the plugin itself.

I will open a separate issue.

**Comment by kamilic** [comment]
any progress?
