### ISSUE TITLE
Conflict with eslint-plugin-flowtype

### ISSUE THREAD

**Issue by iGarym** [vuejs/eslint-plugin-vue#475]
## Description
Init repo by `vue init webpack **`, with `eslint/airbnb`. Add eslint-plugin-flowtype.

```
Use the latest vue-eslint-parser.
```

Change `plugin:vue/recommended` to `plugin:vue/base`, works fine.

## Versions
- babel-eslint: 8.2.1
- eslint: 4.15.0
- eslint-plugin-vue: 4.5.0
- eslint-plugin-flowtype: 2.46.3

## Eslint config
```
root: true,
parserOptions: {
    parser: 'babel-eslint'
},
extends: [
    'airbnb-base',
    'plugin:vue/recommended',
    'plugin:flowtype/recommended'
],
plugins: [
    'vue',
    "flowtype"
]
```

**Comment by michalsnik** [comment]
Hey @iGarym ! It looks like flowtypes recommended configuration sets `parser` to `babel-eslint`, and in order to parse Vue single file components we have to use custom `vue-eslint-parser` that we set in our config. Please try to reorder your `extends` list, so that `vue` comes after `flowtype` and let me know if it works

**Comment by iGarym** [comment]
@michalsnik  Wow, it works fine when i reorder the `extends` list! Although this answer comes a bit late, i have removed flowtype from my project, 233. Anyway thanks!
