### ISSUE TITLE
html-no-self-closing shouldn't be part of the recommended config

### ISSUE THREAD

**Issue by Mouvedia** [vuejs/eslint-plugin-vue#48]
**What did you expect to happen?**

`html-no-self-closing` should not have been included. I don't see why it should be the default. It's a preference. People used to XHTML won't like that.

**What actually happened?**

`html-no-self-closing` was enabled when using `plugin:vue/recommended`.

**Comment by mysticatea** [comment]
Thank you for this issue.

I agree.

That rule has been created in an invalid assumption: HTML does not support self-closing elements, so Vue.js as well. I have learned that Vue.js supports self-closing elements in #29.

Currently, I think that we should remove `html-no-self-closing` rule entirely then create new `html-self-closing` rule which people can configure `always`/`never` to use self-closing elements. Of course, `plugin:vue/recommended` should not include the new stylistic rule.

**Comment by johnmerced** [comment]
I noticed this as well a couple days ago - Looking forward for this change!

**Comment by michalsnik** [comment]
ATM I'll just disable this rule in default configuration, as otherwise we'd need to update major version which is better to be ommited in this beta period. Let's come to a point where we have a stable ground, and then we can remove unnecessary rules and activate new ones in default configuration at once with official `v4`, that is coming our way. cc @mysticatea
