### ISSUE TITLE
`attribute-hyphenation` rule has no effect on event attributes

### ISSUE THREAD

**Issue by churkin** [vuejs/eslint-plugin-vue#586]
ESLint Version: 5.4.0
eslint-plugin-vue Version: 4.7.1

Rule:
`"vue/attribute-hyphenation": [2, "always"]`

Code:
```
<data-grid
  :showBorders="true"
  keyExpr="ID"
  @selectionChanged="onSelectionChanged"
>
```

**I get two errors, but should three:**

  6:7  error  Attribute ':showBorders' must be hyphenated  vue/attribute-hyphenation
  8:7  error  Attribute 'keyExpr' must be hyphenated       vue/attribute-hyphenation

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.

**Comment by michalsnik** [comment]
This is an expected behaviour @churkin But it might be worth it to add an extra rule for forcing hypenation in events too, the rule could both report:
- listener `@someEvent=""` 
- emitter `this.$emit('someEvent')` (in template and script tag)
and automatically fix all of them 👍

This seems like a good rule proposition, especially in regard to info from official documentation: https://vuejs.org/v2/guide/components-custom-events.html

> Unlike components and props, event names will never be used as variable or property names in JavaScript, so there’s no reason to use camelCase or PascalCase. Additionally, v-on event listeners inside DOM templates will be automatically transformed to lowercase (due to HTML’s case-insensitivity), so v-on:myEvent would become v-on:myevent – making myEvent impossible to listen to.

I looked at the opened issues, and it seems we already have this proposal here: https://github.com/vuejs/eslint-plugin-vue/issues/356

So I'm closing this issue in favour of the former one, let's continue discussion there :)

**Comment by acacia314** [comment]
@michalsnik I don't think [#356](https://github.com/vuejs/eslint-plugin-vue/issues/356) addressed the hyphenation of the event listener attribute, eg `@someEvent` is still allowed and there's no rule to enforce '@some-event' format like there is for attributes with attribute-hyphenation.
