### ISSUE TITLE
False invalid v-on rule, eslint

### ISSUE THREAD

**Issue by atilkan** [vuejs/eslint-plugin-vue#614]
I checked the docs and i am using it correctly.
This is error:
<img width="136" alt="screen shot 2018-10-18 at 04 06 00" src="https://user-images.githubusercontent.com/1254613/47125286-42ee4a00-d28b-11e8-892d-6bc627e016b8.png">
This is warning:
<img width="466" alt="screen shot 2018-10-18 at 04 07 20" src="https://user-images.githubusercontent.com/1254613/47125309-5ac5ce00-d28b-11e8-98b4-79bc7f820a4b.png">

VSCode: 1.28.1
Vetur: 0.13.0
Mac Mojave

**Comment by armano2** [comment]
can you provide example?

**Comment by atilkan** [comment]
I can't unfortunately. Because it doesn't happen always. This brings the question if i do something wrong but it is fairly simple example. Only difference here is i am inside a component inside another component.
It excepts this syntax btw.
<img width="152" alt="screen shot 2018-10-18 at 05 11 36" src="https://user-images.githubusercontent.com/1254613/47127087-594cd380-d294-11e8-8325-920bcbc061d9.png">
also
<img width="169" alt="screen shot 2018-10-18 at 05 14 49" src="https://user-images.githubusercontent.com/1254613/47127192-c496a580-d294-11e8-9894-952927acd62f.png">
but not this.
<img width="484" alt="screen shot 2018-10-18 at 05 17 32" src="https://user-images.githubusercontent.com/1254613/47127267-26570f80-d295-11e8-8832-595a0c5ba550.png">

**Comment by atilkan** [comment]
Extra: (very interesting) 
**Care the first line too**
<img width="495" alt="screen shot 2018-10-18 at 06 43 51" src="https://user-images.githubusercontent.com/1254613/47130211-41c81780-d2a1-11e8-96bc-cc686fcfcb5a.png">

**Comment by atilkan** [comment]
I think it cause error because it is reserved keyword. But should throw related error.
<img width="495" alt="screen shot 2018-10-18 at 06 43 51" src="https://user-images.githubusercontent.com/1254613/47130276-953a6580-d2a1-11e8-9be7-694fd649d822.png">

**Comment by mysticatea** [comment]
You cannot use `delete` as a variable name because `delete` is a reserved word in JavaScript. Also, Vue.js will throw a compile error on the reserved word.

https://jsfiddle.net/q7kzrx02/
![image](https://user-images.githubusercontent.com/1937871/47133168-74463480-d2e2-11e8-9ada-3e78b9a549cd.png)

Now, `vue-eslint-parser` parses the source code `delete`, but it's a syntax error because the delete expression requires an argument (e.g., `delete obj.a`). This is the reason that `vue/no-parsing-error` said "Unexpected end of expression".
As the result of the parsing error, the attribute `@click` has no value on AST. This is the reason that `vue/valid-v-on` said "'v-on' directive requires that attribute value or verb modifiers".

Therefore, `@click="delete"` is an invalid `v-on` directive and `valid-v-on` reports it correctly.
However, maybe we can improve the error message for more understandable.

**Comment by atilkan** [comment]
Thanks for the explanation. I figured that too. But i thought it ends up as object prop and should be ok.

**Comment by metheany** [comment]
I solved this by just replace other words, Example: deleteSomething
