### ISSUE TITLE
style-indent

### ISSUE THREAD

**Issue by AdamWei1992** [vuejs/eslint-plugin-vue#883]
i don't know if there is any style-indent configuration rule.
just like vue/html-indent and vue/script-indent

**Comment by victorwpbastos** [comment]
Would be great to have it.

**Comment by BrandonYeager** [comment]
I would love this option as well!

I spent a few hours trying to switch the default generated project to use tabs instead of spaces and it appears that to accomplish this in the style section would require extra packages and not work well with the cli linter.

Do to this limitation, we ended up scrapping the conversion and will live with spaces for now.

**Comment by WillGibson** [comment]
We could do with this too. I'm going to try and put a PR together.

**Comment by ota-meshi** [comment]
Thank you for this issue.

Similar issue have been closed. See the related issue for details.

#619
