### ISSUE TITLE
Parsing error when using bitshift << operator in template interpolation

### ISSUE THREAD

**Issue by panstromek** [vuejs/eslint-plugin-vue#939]
**Tell us about your environment**	
* **ESLint version:**
6.1.0	
* **eslint-plugin-vue version:**	
5.2.3.
* **Node version:**	
12.4.0

**Please show your full configuration:**

```js
module.exports = {
  root: true,

  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module'
  },

  env: {
    browser: true
  },

  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/recommended',
    '@vue/standard'
  ],

  // required to lint *.vue files
  plugins: [
    'vue'
  ],

  globals: {
    'ga': true, // Google Analytics
    'cordova': true,
    '__statics': true,
    'process': true
  },

  // add your custom rules here
  rules: {
    // allow async-await
    'generator-star-spacing': 'off',
    // allow paren-less arrow functions
    'arrow-parens': 'off',
    'one-var': 'off',

    'import/first': 'off',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/default': 'error',
    'import/export': 'error',
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': 'off',
    'prefer-promise-reject-errors': 'off',
    'camelcase': 'off',
    'vue/singleline-html-element-content-newline': 'off',
    'vue/max-attributes-per-line': ['error', {
      'singleline': 8,
      'multiline': {
        'max': 1,
        'allowFirstLine': false
      }
    }],

    // allow console.log during development only
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    // allow debugger during development only
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}

```

**What did you do?**	

```vue
<div>{{ i << 0 }}</div>
```

**What did you expect to happen?**
Nothing

**What actually happened?**
ESLint: Parsing error: invalid-first-character-of-tag-name. (vue/no-parsing-error)

**Comment by janispritzkau** [comment]
The same happens with the `<` and `<=` operator.

**Comment by ota-meshi** [comment]
Thank you for this issue.

This is intentional behavior. 
See same issue #370 for more details.

We recommend using computed properties or `&lt;`.
If you do not want to rewrite the source code, you can use the following options:

https://eslint.vuejs.org/rules/no-parsing-error.html#options

You can check with [DEMO].

[Demo]: https://mysticatea.github.io/vue-eslint-demo/#eJyNV9tunDoU/RXEYxUrR+cxGvUn2reTPhjYgBtjE9vMDI3y72fZBmNgIlVRlXjtjfdtedn9KGvdUPlSXhwNo+SOvr+qorg04vr946MQxeVS/FN8fl6ePfKqLs+Z38XWRowOfz1/K8hKoVxxnehZaTZyY4XqGBmjzUvxX/j9VHy8lkJduRQNa4WxjtU9N7x2ZJhumeMdU3yg1/KlaLm09Pnr27OPucQpn0ozSbLlywfSVtaZqXbaMDuNZMqXf5/KFqtGGKqd0CogHTm/uyE3mYggu5pbYg3VEsG9p00Gya1l+Ce6zVkPqIaYoo79IaM3XDUnV2W1pHzpHrg4rlz4XKQ0o8UZLZFqR/cVbKiaum6pLqwlOWJXviEonnHT2R0QCxloqMjsLW8054AUNYYZOrKiGLCbs8mEvfbGkfuuqh2YFvdDyXR3hrNKozNc+Uhub7E0iBXB2KXrjZ66PkGTqg87dlJXXB5AoRSSfTTVlXKhs2NCDdYTnNmtF47syOvUgkHcqWEBAh0wZ8ertJ2iG7PzUGm5Irr6jbqkTC66djxZDcWkaAOQx7L7ilmS7aEg6w+Rn63h28hcLyyrCESnjPcwTKqhdlugUJwCFDFM0gkcTdpshjimW8kMsrwlHEmFIuYDCt7znKeTmiz2lbyireAFBC83CCURSEi25mMMhT4hKWZ7bVyPtgbQ0PuEI8tmQTIi+JIJq3gMGWfn5pF0rM9LTGgKq8DQN3KhlVCb3KpvZ9Q5I6oJbO/nsSe1VbWzWqZNs/TVGyqp67fTZj40JuDmpYseq6FdMp2kgOhh4KzhqpN7kKAAi1Bdd5ZRK2/zMgjeslVt/bHJw9O7/0nL3g0S51QHzV27Ap6muX/pdKwrOFFg/CIpCRVgmHJ77H3Sjg5+gcpLnGT5be+eEXajiEchRqcMBu7qnm2taIWk0I/MAxKzjQuHgO0KTZRnsRpJod9eYENvD30ZJihy3ft+Q9RGLQMxTnmFkYxGI5yXx/08wHduZwgVZuZTn/zRW5xF1iD4rUKI48qRaG5Chu0UxnNl/iq7MtHm9r2Ab+Ai4ltPcnvoRq42j67o3GDIkrki/2MkGBAgqApqdfyeGy3uCxi2uTXc8Z2DaIhR24Lz9i/atIov7gKwERoBwffqGL5NleZfpLOCvB/iSLHRt73p7pA2ZysHcuOiaaki+8C4Y3MUvTA1dhOuj1PMzdfAyIQselhPRp7PQVChtVGHBHzLokYceLiK6TYGYU/GhXmh8WdjUCVczSNE+mQNgb0Ws+wB9rXXObaBtuzfY7k10j6fX7KEW+CLzP1ejyi1bRNfkEcJ862T9PdKETiJTVpxZ3q0B3xS3Mw7PFzWmYonQ6QJRIbueGMl+MoqZHi4VYKffwQFVfLPjL3p4B1vy5XyRmt3sMUgJxCCzd9OKK54ykUox09gTvYV2/F9BR9sOOC/IWfH7H7eoPoceTRnDK+M2wn0Bx7g51MZqfBD/IlfxuXP2b9UyvgWfCrDAww1lXgdGqLy839NfI6A

**Comment by panstromek** [comment]
Hmm. I see, kinda weird. Thanks for pointing that out.

I feel like this rule should be renamed to "no-html-parsing-error", because it's a bit misleading - error is related to HTML, there is no parsing error in Vue (probably not worth a breaking change, though).

I see this might be very good guard when using DOM templates but for normal Vue development with SFCs it's kinda pointless.
