### ISSUE TITLE
Incompatibility with typescript-eslint@2

### ISSUE THREAD

**Issue by sem4phor** [vuejs/eslint-plugin-vue#944]
**Tell us about your environment**	
* **ESLint version:**	5.16.0
* **eslint-plugin-vue version:**	5.02.3
* **Node version:**	 11.6.0

**Please show your full configuration:**
https://github.com/sem4phor/vue-typescript-eslint

**What did you do?** 
I created a new repository with vue-cli3 
I installed all dependencies for adding typescript-eslint@2.0.0
I upgraded typescript eslint to v2.0.0 (latest major release) and changed configuration according to: https://github.com/typescript-eslint/typescript-eslint/issues/853#issuecomment-521535334
Then i ran `npm run lint`

**What did you expect to happen?**
The template of the .vue files are linted without a parser error

**What actually happened?**
The parser did fail to parse the template (See error message in README of bug repro repo)

I am not sure if thats an issue of eslint-plugin -vue, the configuration or typescript-eslint. Maybe someone can help me out.

**Comment by ota-meshi** [comment]
I removed `vue/no-parsing-error` by changing the setting.

I set `parserOptions.createDefaultProgram` to `true` and excluded `.vue` from `include` in `tsconfig.eslint.json`.

`vue-eslint-parser` tries to pass the script part of the vue file to `@typescript-eslint/parser`, but `@typescript-eslint/parser` may return the analysis result of another source code.
This is the source code contained in the cache used for parsing other files.
The source code contained in this cache is the result of all the lines in the vue file.
Since the analysis by `@typescript-eslint/parser` fails, the vue file is reported as a parsing error.

If you exclude `.vue` from `include` in `tsconfig.eslint.json`, it will not be cached in other file analysis.

But I don't know if this configuration change is correct.

**Comment by IlCallo** [comment]
@ota-meshi as written [here](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#configuration) into `createDefaultProgram` description, you are more or less disabling v2 performance fixes, that's why its working.

Gonna reference this issue on their issue tracker too.
@mysticatea may be the right person to deal with this probably, if I remember well he was the one who wrote `vue-eslint-parser`.

Also, seems like that package still depends on ESLint 5 and didn't updated to ESLint 6, this may be one of the problems (https://github.com/mysticatea/vue-eslint-parser/issues/54).

**Comment by sem4phor** [comment]
@ota-meshi did your performance improve when comparing v2 and v1.x ?

typescript-eslint-parser docs:
```
createDefaultProgram - default false. This option allows you to request that when the project setting is specified, files will be allowed when not included in the projects defined by the provided tsconfig.json files. However, **this may incur significant performance costs**, so this option is primarily included for backwards-compatibility. See the project section for more information.
```

**Comment by GodofHope** [comment]
I still catch a little confused after seeing this and the referened issure. Is it a bug actually? Or not a bug, just confliction caused by them which needs extra configuration?  So could  you how I solve it now?

**Comment by IlCallo** [comment]
AFAIK you cannot solve it.
Seems like someone [is working on it](https://github.com/typescript-eslint/typescript-eslint/issues/890) tho, so you can subscribe to that issue and try `@typescript-eslint/eslint-plugin@canary` every while

**Comment by sem4phor** [comment]
Fixed in https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.5.0
