### ISSUE TITLE
`vue/v-on-function-call` can not autofix when set to `always `

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/eslint-plugin-vue#973]
**Tell us about your environment**	
* **ESLint version: 6.5.1**	
* **eslint-plugin-vue version: 5.2.3**	
* **Node version: 10.16.3**	

**Please show your full configuration:**

```js
module.exports = {
  root: true,
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true
    }
  },
  env: {
    browser: true,
    node: true,
    es6: true
  },
  plugins: [
    'vue'
  ],
  rules: {
    'vue/v-on-function-call': [2, 'always']
  }
};
```

**What did you do?**	

```vue
<template>
  <button @click="closeModal">Close</button>
</template>

<script>
export default {
  methods: {
    closeModal() {}
  }
}
</script>
```

**What did you expect to happen?**
Can be automatically fix to:
```vue
<template>
  <button @click="closeModal()">Close</button>
</template>

<script>
export default {
  methods: {
    closeModal() {}
  }
}
</script>
```

**What actually happened?**
Can't be fixed automatically

**Extra information**
If set to `never`, `@click="closeModal()"` can be automatically fix to `@click="closeModal"`

**Comment by ota-meshi** [comment]
Thank you for this issue.

The `vue/v-on-function-call` rule is not autofix when `always` is set.
Because if autofix changes  `@click="closeModal"` to `@click="closeModal()"`, the arguments will be truncated.
If you want to autofix without problems, autofix should be changed to  `@click="(...args)=>closeModal(...args)"`, but this is not the user's intended modification.

**Comment by yangmingshan** [comment]
Thank you for the explanation.
